name: k8s-job
description: Runs your build step as a kubernetes job
author: https://github.com/buildkite
requirements:
  - jq
  - kubectl
  - kustomize
configuration:
  properties:
    metadata:
      type: object
      properties:
        annotations:
          type: object
        namespace:
          type: string
          default: default
    pod-spec:
      type: string
    cleanup:
      type: boolean
    mount-source:
      type: boolean
    timeoutInSeconds:
      type: number
  required:
    - pod-spec
  additionalProperties: false
