steps:
  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.2.0:
          id: k8s-job

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
